# Copyright (C) 2019 Moxa Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

stages:
    - build
    - release

build_azure-iot-sdk-c:
    stage: build
    tags:
        - 4530-arm-linux-gnueabihf-5.1
    only:
        - branches
    script:
        - ./setup.sh
        - ./build.sh
        - shopt -s extglob
        - rm -rf sample/binary output upload
        - mkdir -p upload/azure-iot-sdk-c
        - cp -r !(upload) upload/azure-iot-sdk-c
        - scm upload $CI_COMMIT_REF_NAME

release_azure-iot-sdk-c:
    stage: release
    tags:
        - 4530-arm-linux-gnueabihf-5.1
    only:
        - tags
    variables:
        REPOSITORY: "git@github.com:kbwilson89/azure-iot-sdk-c.git"
        BRANCH: "master"
    script:
        - ./setup.sh
        - ./build.sh
        - shopt -s extglob
        - rm -rf sample/binary output upload
        - mkdir -p upload/azure-iot-sdk-c
        - cp -r !(upload) upload/azure-iot-sdk-c
        - scm upload $CI_COMMIT_REF_NAME
        - git checkout -B $BRANCH
        - git push $REPOSITORY $BRANCH --tags --force
